# Generated by Django 4.0 on 2021-12-07 10:40

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 7, 10, 40, 54, 691228, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='user',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 7, 10, 40, 54, 691244, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='usercredit',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 7, 10, 40, 54, 692339, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='usercredit',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 7, 10, 40, 54, 692350, tzinfo=utc)),
        ),
    ]
